# Generated by Django 3.2 on 2021-04-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
